# non-functional example
version: '2'

services:
  web:
    image: web-db
    build: .
    ports:
      - 80:5000
    env_file:
      - db.env
    entrypoint: ./start.pl --init --command shotgun
    depends_on:
      - db
  db:
    image: mysql
    env_file:
      - db.env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: "driver-name"
    driver_opts:
      - opt1: "foo"
      - opt2: "bar"

